# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7324d4367f9e633f74d94e23c44bdfefa133beccc12444c2a506e296b4ad20a46a6ed7da66d07846910423535a6dd109ff62877f98f534220011c3edf95d869a

test:
  secret_key_base: 9cad40349ce359ac8e39d82e98ef28daa02437415e1b5e9017dc76edccafebd0da405c281b7d8b9cc9fdef94d1f371cc28d9e14c4048eab49c920a9a49a35ee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
